### ISSUE TITLE
Improve README.md 

### ISSUE THREAD

**Issue by diegomrt** [RoboticsLabURJC/2019-tfm-omar-garrido#4]
Besides redirecting to the content in the TFM blog, README.md should include a brief explanation of:

- **Parameters of the rosified node:** Goal of each one, default values, etc. 
- **Package .launch files:**  enumerate files available in the launch folder, explain them briefly.

**Comment by omar-ogm** [comment]
Close, all the information is now on https://roboticslaburjc.github.io/2019-tfm-omar-garrido/install/#launch-files-and-parameters
